import os
from dotenv import load_dotenv

# This looks for the .env file and loads your secrets into memory
load_dotenv()

DEV_EMAIL = os.getenv("DEV_EMAIL")
APP_PASSWORD = os.getenv("APP_PASSWORD")

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dm4f7tgEA1hFWPN4xyhMvGd9S9-4on5J
"""

from google.colab import drive
import os


if not os.path.exists('/content/drive/MyDrive'):
    print("Mounting Drive...")
    drive.mount('/content/drive', force_remount=True)
else:
    print("✅ Drive is already mounted! We have persistent storage.")


!apt-get update && apt-get install -y zstd


!curl -fsSL https://ollama.com/install.sh | sh

import subprocess
import time

print("\nStarting Ollama server...")
process = subprocess.Popen(["ollama", "serve"])
time.sleep(3) 

print("Pulling the Mistral model (this might take a minute or two)...")
!ollama pull mistral

print("✅ Ollama is running and Mistral is ready!")


!apt-get update && apt-get install -y zstd


!curl -fsSL https://ollama.com/install.sh | sh

import subprocess
import time


print("\nStarting Ollama server...")
process = subprocess.Popen(["ollama", "serve"])
time.sleep(3) 

print("Pulling the Mistral model (this might take a minute or two)...")
!ollama pull mistral

print("✅ Ollama is running and Mistral is ready!")

import requests


url = "http://localhost:11434/api/generate"


payload = {
    "model": "mistral",
    "prompt": "Explain Retrieval-Augmented Generation (RAG) in exactly one short sentence.",
    "stream": False # We set this to False so it waits for the full answer before printing
}

print("Sending request to local Mistral model...\n")
response = requests.post(url, json=payload)


print("🤖 Mistral says:")
print(response.json()['response'])

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


# PUT YOUR DEV ACCOUNT CREDENTIALS HERE
DEV_EMAIL = "rag.dev.project@gmail.com"
APP_PASSWORD = "xdts lblv nycp gfie"

emails_to_send = [
    {
        "sender_name": "Sarah (Manager)",
        "subject": "URGENT: Project Alpha Deployment Delayed",
        "body": "Team, we have a critical blocker. The database migration for Project Alpha failed staging tests. We are pushing the deployment deadline from this Friday to next Wednesday, the 14th. David, please halt the frontend release until this is resolved."
    },
    {
        "sender_name": "David (Frontend)",
        "subject": "Re: URGENT: Project Alpha Deployment Delayed",
        "body": "Understood Sarah. I will pause the UI push. However, this means I have free bandwidth this week. Should I pivot to the Q3 Analytics Dashboard tickets?"
    },
    {
        "sender_name": "HR Notifications",
        "subject": "Leave Approval: Alex Chen",
        "body": "This is an automated notification. Alex Chen (Backend Engineering) has approved PTO from Monday the 12th through Friday the 16th. Please ensure all code handoffs are completed by Friday."
    },
    {
        "sender_name": "Alex Chen",
        "subject": "Handoff Notes before my PTO",
        "body": "Hey team, since I am out next week, I've assigned the remaining API security patches to Marcus. Marcus, the documentation is in the main wiki. Let me know if you need a quick sync before Friday."
    },
    {
        "sender_name": "Marcus (Dev)",
        "subject": "Weekly Workload Update",
        "body": "Sarah, just a heads up. With Alex handing off the API patches to me, and my current sprint tasks, I am severely overloaded this week. I will likely miss the deadline for the Client Onboarding module. Can we deprioritize it?"
    }
]

print("Connecting to Gmail SMTP server to generate synthetic data...")
try:
    
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(DEV_EMAIL, APP_PASSWORD)

    for i, data in enumerate(emails_to_send):
        msg = MIMEMultipart()
        msg['From'] = f"{data['sender_name']} <{DEV_EMAIL}>"
        msg['To'] = DEV_EMAIL
        msg['Subject'] = data['subject']
        msg.attach(MIMEText(data['body'], 'plain'))

        server.send_message(msg)
        print(f"✅ Sent email {i+1}/5: {data['subject']}")

    server.quit()
    print("\n🎉 Synthetic data successfully injected into your live inbox!")

except Exception as e:
    print(f"❌ Error: {e}")

import imaplib
import email
from email.header import decode_header
import re

# PUT YOUR CREDENTIALS HERE

EMAIL_ACCOUNT = "rag.dev.project@gmail.com"
APP_PASSWORD = "xdts lblv nycp gfie" 


def clean_text(text):
    """Removes extra spaces, newlines, and weird characters."""
    if not text: return ""
    text = re.sub(r'\s+', ' ', str(text))
    return text.strip()

def fetch_latest_emails(num_emails=5):
    print("Connecting to Gmail via IMAP...")
    try:
        # Connect to the server
        mail = imaplib.IMAP4_SSL("imap.gmail.com")
        mail.login(EMAIL_ACCOUNT, APP_PASSWORD)

        # Select the inbox
        mail.select("inbox")

        # Search for all emails
        status, messages = mail.search(None, "ALL")
        email_ids = messages[0].split()

        # Get the latest 'num_emails' IDs
        latest_email_ids = email_ids[-num_emails:]

        extracted_emails = []

        print(f"Fetching your {num_emails} most recent emails...\n")
        print("-" * 50)

        for e_id in reversed(latest_email_ids):
            status, msg_data = mail.fetch(e_id, "(RFC822)")

            for response_part in msg_data:
                if isinstance(response_part, tuple):
                    msg = email.message_from_bytes(response_part[1])

                    # Decode Subject
                    subject, encoding = decode_header(msg["Subject"])[0]
                    if isinstance(subject, bytes):
                        subject = subject.decode(encoding if encoding else "utf-8", errors="ignore")

                    # Get Sender
                    sender = msg.get("From")

                    # Get Body
                    body = ""
                    if msg.is_multipart():
                        for part in msg.walk():
                            if part.get_content_type() == "text/plain":
                                try:
                                    body = part.get_payload(decode=True).decode(part.get_content_charset() or "utf-8", errors="ignore")
                                    break # Just get the first plain text part
                                except:
                                    pass
                    else:
                        body = msg.get_payload(decode=True).decode(msg.get_content_charset() or "utf-8", errors="ignore")

                    # Clean the data
                    clean_subject = clean_text(subject)
                    clean_body = clean_text(body)[:500] # Grab first 500 chars for preview

                    extracted_emails.append({
                        "sender": sender,
                        "subject": clean_subject,
                        "body": clean_body
                    })

                    print(f"📩 FROM: {sender}")
                    print(f"📝 SUBJECT: {clean_subject}")
                    print(f"📄 PREVIEW: {clean_body}...\n")
                    print("-" * 50)

        # Logout
        mail.logout()
        return extracted_emails

    except Exception as e:
        print(f"❌ Error: {e}")
        return []


my_data = fetch_latest_emails(5)


# CALENDAR DATA & NORMALIZATION


# This mimics the JSON schema returned by the official Google Calendar API
calendar_api_response = [
    {
        "kind": "calendar#event",
        "summary": "Project Alpha Sync",
        "description": "Discussing the database deployment blockers mentioned by Sarah.",
        "start": {"dateTime": "2026-04-24T10:00:00-07:00"},
        "end": {"dateTime": "2026-04-24T11:00:00-07:00"},
        "organizer": {"email": "sarah.manager@techcorp.com"}
    },
    {
        "kind": "calendar#event",
        "summary": "Alex's PTO Handoff",
        "description": "Finalizing API security patch handoff to Marcus.",
        "start": {"dateTime": "2026-04-25T14:00:00-07:00"},
        "end": {"dateTime": "2026-04-25T14:30:00-07:00"},
        "organizer": {"email": "alex.chen@techcorp.com"}
    },
    {
        "kind": "calendar#event",
        "summary": "Weekly Frontend Sync",
        "description": "Standard weekly sync. David to update on Q3 Analytics.",
        "start": {"dateTime": "2026-04-26T09:00:00-07:00"},
        "end": {"dateTime": "2026-04-26T10:00:00-07:00"},
        "organizer": {"email": "david.frontend@techcorp.com"}
    }
]

print(f"✅ Fetched {len(calendar_api_response)} calendar events.")


# THE NORMALIZATION LAYER (Combining Emails + Calendar)


unified_documents = []
metadata_store = [] 

# 1. Process Emails 
for email in my_data:
    # Tagging it as an [EMAIL] so the AI knows the context
    text_representation = f"[EMAIL] From: {email['sender']} | Subject: {email['subject']} | Body: {email['body']}"
    unified_documents.append(text_representation)
    metadata_store.append({"type": "email", "source": email['sender']})

# 2. Process Calendar Events
for event in calendar_api_response:
    # Tagging it as a [MEETING] so the AI knows the context
    text_representation = f"[MEETING] Title: {event['summary']} | Time: {event['start']['dateTime']} | Organizer: {event['organizer']['email']} | Details: {event.get('description', 'No details')}"
    unified_documents.append(text_representation)
    metadata_store.append({"type": "meeting", "source": event['organizer']['email']})

print(f"✅ Normalization complete! We now have {len(unified_documents)} total organizational records ready for the AI.\n")

print("--- SNEAK PEEK OF UNIFIED DATA ---")
print(unified_documents[0]) # Should be an email
print(unified_documents[-1]) # Should be a meeting


# GENERATE EMBEDDINGS

from sentence_transformers import SentenceTransformer

print("Loading embedding model (all-MiniLM-L6-v2)...")
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

print("Translating all Emails and Meetings into vector embeddings...")
embeddings = embedding_model.encode(unified_documents)

print("✅ Embeddings generated successfully!")
print(f"We have {embeddings.shape[0]} vectors (documents).")


# PERSISTENT VECTOR DB
!pip install -q faiss-cpu
import faiss
import sqlite3
import os

print("Setting up the Vector Database (FAISS)...")
dimension = embeddings.shape[1]
faiss_index = faiss.IndexFlatL2(dimension)
faiss_index.add(embeddings)

# Saving the FAISS index permanently to Google Drive
os.makedirs('/content/drive/MyDrive/RAG_Project', exist_ok=True)
faiss.write_index(faiss_index, '/content/drive/MyDrive/RAG_Project/faiss_index.bin')
print("✅ Saved FAISS math to Google Drive!")

print("\nSetting up persistent SQLite Database...")
db_path = '/content/drive/MyDrive/RAG_Project/org_memory.db'
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

cursor.execute('''CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY, text_content TEXT, doc_type TEXT, source TEXT)''')
cursor.execute('DELETE FROM documents')

for i, text in enumerate(unified_documents):
    try:
        doc_type = metadata_store[i]['type']
        source = metadata_store[i]['source']
    except NameError:
        doc_type = "unknown"
        source = "unknown"
    cursor.execute('INSERT INTO documents (id, text_content, doc_type, source) VALUES (?, ?, ?, ?)', (i, text, doc_type, source))

conn.commit()
print(f"✅ Saved {len(unified_documents)} text documents to SQLite in your Google Drive!")

import subprocess
import time
import requests

print("Waking up the AI brain (restarting Ollama)...")

subprocess.Popen(["ollama", "serve"])
time.sleep(3) 

try:
    response = requests.get("http://localhost:11434/")
    print("✅ Ollama is awake and ready for your question!")
except Exception as e:
    print("❌ Still sleeping, try running this cell one more time.")


# STEP 5: THE RAG PIPELINE 

import requests
import numpy as np

# 1. The User's Question
user_question = "Who is overloaded this week and why?"
print(f"👤 USER: {user_question}\n")

# 2. Embed the Query 
print("🔍 Step 1: Searching the vector database for relevant context...")
# reshaping it to a 2D array for FAISS
query_vector = embedding_model.encode([user_question])

# 3. Retrieve from FAISS (Find the top 3 closest matches)
k = 3 # We want the top 3 most relevant documents
distances, indices = faiss_index.search(query_vector, k)

# 4. Fetch the actual text from SQLite
retrieved_context = ""
print("📂 Step 2: Retrieving documents from SQLite...")
for i, doc_id in enumerate(indices[0]):
    # We convert numpy int to native python int for SQLite
    cursor.execute('SELECT text_content FROM documents WHERE id = ?', (int(doc_id),))
    result = cursor.fetchone()
    if result:
        print(f"   -> Found Match {i+1}: {result[0][:75]}...") # Print a preview
        retrieved_context += f"- {result[0]}\n"

# 5. Construct the Prompt (The "Augmented Generation")
# We explicitly tell the AI to ONLY use our data. This stops hallucinations.
final_prompt = f"""
You are an intelligent organizational assistant.
Use ONLY the following context to answer the user's question. If the answer is not in the context, say "I don't know based on the provided data."

Context:
{retrieved_context}

Question: {user_question}

Answer clearly and concisely:
"""

# 6. Ask the Local AI
print("\n🧠 Step 3: Sending context to local Mistral AI for reasoning...\n")
url = "http://localhost:11434/api/generate"
payload = {
    "model": "mistral",
    "prompt": final_prompt,
    "stream": False
}

response = requests.post(url, json=payload)

# 7. The Result!
print("==========================================")
print("🤖 AI ASSISTANT RESPONSE:")
print(response.json()['response'])
print("==========================================")